### ISSUE TITLE
Function working directory incorrect

### ISSUE THREAD

**Issue by jespersh** [MarcStan/LetsEncrypt.Azure#1]
The `execute` function fails for unknown reason, but when I attempt the `renew` function directly:
```
[Information] Executing 'renew' (Reason='This function was programmatically called via the host APIs.', Id=cd1299ff-3bf7-458f-b855-b7fe2ba889af)
[Warning] No config files found. Placing config/sample.json in storage!
[Error] Executed 'renew' (Failed, Id=cd1299ff-3bf7-458f-b855-b7fe2ba889af)

Could not find file 'D:\Program Files (x86)\SiteExtensions\Functions\2.0.12673\32bit\sample.json'.
```

When attempting `execute`:
```
[Information] Executing 'execute' (Reason='This function was programmatically called via the host APIs.', Id=0d2c3209-c74b-40a0-9499-d0918095409e)
[Warning] No config files found. Placing config/sample.json in storage!
[Information] Executed 'execute' (Succeeded, Id=0d2c3209-c74b-40a0-9499-d0918095409e)
```

It doesn't show a failure reason because this exception silencing everything:
https://github.com/MarcStan/LetsEncrypt.Azure/blob/fd6ee43613b59181811996563e41319d46bb7723/LetsEncrypt.Func/AutoRenewal.cs#L49-L55

There seems to be a `ExecutionContext.FunctionAppDirectory` that could work

**Comment by MarcStan** [comment]
Sorry for the delay, for some reason I didn't receive emails for this repository and missed your issue.

I do appreciate the pull request and it looks good!

Thank you very much for the help.
